# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-07-28 18:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0122_referralhubpage_extra_content_and_more"),
        ("cms", "0123_alter_articledetailpage_sticker_and_more"),
    ]

    operations = []
