# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

# Generated by Django 5.2.15 on 2026-08-06 16:33

from django.db import migrations

import springfield.cms.fields


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0125_referralhubpage_extra_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="referralgetfirefoxpage",
            name="lower_content",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
        migrations.AddField(
            model_name="referralgetfirefoxpage",
            name="upper_content",
            field=springfield.cms.fields.StreamField(blank=True, block_lookup={}, null=True),
        ),
    ]
